export enum ReportReasonEnum {
    SPAM = 'SPAM',
    INAPPROPRIATE = 'INAPPROPRIATE',
    COPYRIGHT = 'COPYRIGHT',
    HARASSMENT = 'HARASSMENT',
    MISINFORMATION = 'MISINFORMATION',
    OTHER = 'OTHER',
}
